# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'DenApp' do
  use_frameworks!

  pod 'KeychainSwift'
  pod 'IQKeyboardManagerSwift'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'

end
